version: '3'
# Creating network "visits_default" with the default driver
services:
  redis-server:    # this name will be exposed in the network as the host name
    image: 'redis'
  node-app:        # this name will be exposed in the network as the host name
    restart: on-failure # 'no'(no===false), always, on-failure, unless-stopped
    build: .
    ports:
      - "4001:8081"

